version: '3.8'

services:
  db:
    image: sqldb:8.0 # Use official image, remove custom tag
    container_name: project2-db-1
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: '123'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    image: chandu0303/web:v1 # Only tag your custom web app
    container_name: project-web-1
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:   
